# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaces',
            name='imageid',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
