# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0002_auto_20180420_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='errfaces',
            name='fixstatus',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
