# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-28 08:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0003_errfaces_fixstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFaceSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceset_token', models.CharField(max_length=32, unique=True)),
                ('face_tokens', django.contrib.postgres.fields.jsonb.JSONField()),
                ('face_count', models.IntegerField(null=True)),
                ('outer_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='allfaces',
            name='faceset_outerid',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allfaces',
            name='faceset_status',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='allfaces',
            name='facetoken',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='allfaces',
            unique_together=set([]),
        ),
    ]
