# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0004_auto_20180428_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfaces',
            name='chstamp',
        ),
        migrations.AddField(
            model_name='allfaces',
            name='picname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='allfaces',
            name='pictime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='allfaces',
            name='picpath',
            field=models.CharField(max_length=200),
        ),
    ]
