# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0007_auto_20180501_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaces',
            name='pictime',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
