# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0008_auto_20180501_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='errfaces',
            name='snapint',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='errfaces',
            name='snapseq',
            field=models.IntegerField(null=True),
        ),
    ]
