# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0009_auto_20180501_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaces',
            name='pictime',
            field=models.CharField(default='0001-01-01 00:00:00', max_length=20),
        ),
    ]
