# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0011_auto_20180501_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfaces',
            name='pictime',
            field=models.DateTimeField(null=True),
        ),
    ]
