# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-28 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find', '0012_auto_20180516_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allfaces',
            old_name='picpath',
            new_name='videopath',
        ),
    ]
